command_timeout = 1000
right_format = """$time"""

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "
"Code" = "üë®‚Äçüíª Code"
"Cursos" = "Ó∏ç  Cursos"
"config" = "Ôê£ "

[time]
disabled = false
style = "#939594"
format = "[$time]($style)"

[aws]
style = "bg:#C0E0DE fg:black"
symbol = "‚òÅ "
format = "[ÓÇ∞](fg:black bg:#C0E0DE)[$symbol$profile]($style)[ÓÇ∞](fg:#C0E0DE bg:black)"

[character]
success_symbol = "[‚ùØ](#ff9400)"
error_symbol = "[‚úó](#ff4b00)"

[cmd_duration]
style = "#C0E0DE"
format = "[ÓÇ∞](fg:black bg:#C0E0DE)[Û±ëç Û∞•î $duration](bg:$style fg:black)[ÓÇ∞](fg:$style)"

[directory]
style = "#335170"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[ÓÇ∞](fg:black bg:#335170)[$path[$read_only](bg:$style fg:black)](bg:$style fg:black)[ÓÇ∞](fg:$style)"
read_only = " ÔÄ£ "

[docker_context]
style = "fg:black bg:#094D92"
symbol = "üê≥  "
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$context]($style)[ÓÇ∞](fg:#094D92)"

[git_branch]
style = "#9EEFE5"
format = "[ÓÇ∞](fg:black bg:$style)[ $symbol$branch](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[git_commit]
style = "#9EEFE5"
format = "\b[ ](bg:$style)[\\($hash$tag\\)](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[git_state]
style = "#9EEFE5"
format = "\b[ ](bg:$style)[ \\($state( $progress_current/$progress_total)\\)](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[git_status]
style = "#9EEFE5"
format = "(\b[ ](bg:$style fg:black)$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind[ÓÇ∞](fg:$style))"
conflicted = "[ÔÅ± ](bold fg:88 bg:#9EEFE5)[ ÔëÄ ${count} ](fg:black bg:#9EEFE5)"
staged = "[ÔÅß $count ](fg:black bg:#9EEFE5)"
modified = "[Ô£™ ${count} ](fg:black bg:#9EEFE5)"
renamed = "[ÔÄ´ ${count} ](fg:black bg:#9EEFE5)"
deleted = "[ÔÄî ${count} ](fg:black bg:#9EEFE5)"
untracked = "[?${count} ](fg:black bg:#9EEFE5)"
stashed = "[Ôíá ${count} ](fg:black bg:#9EEFE5)"
ahead = "[ÔÉÆ ${count} ](fg:#523333 bg:#9EEFE5)"
behind = "[ÔÉ≠ ${count} ](fg:black bg:#9EEFE5)"
diverged = "[ÔÅ± ](fg:88 bg:#9EEFE5)[ Ô≠Ä ](fg:black bg:#9EEFE5)[ÔÉÆ ${ahead_count} ](fg:black bg:#9EEFE5)[ÔÉ≠ ${behind_count} ](fg:black bg:#9EEFE5)"

[golang]
symbol = "üöÄ "
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[helm]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol($version)]($style)[ÓÇ∞](fg:#094D92)"

[java]
symbol = "ÔÉ¥ "
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[kotlin]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[kubernetes]
format = "[ÓÇ∞](fg:black bg:#2B50AA)[$symbol$context](fg:black bg:#2B50AA)[ÓÇ∞](fg:#2B50AA)"
disabled = false

[memory_usage]
style = "#C0E0DE"
symbol = "ÔâÄ  üöÄ"
format = "[ÓÇ∞](fg:black bg:#C0E0DE)[$symbol$ram](bg:#C0E0DE fg:black)[ÓÇ∞](fg:#C0E0DE)"
threshold = 1
disabled = false

[nodejs]
style = "green"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol($version)](fg:black bg:#094D92)[ÓÇ∞](fg:#094D92)"

[ocaml]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[package]
disabled = true

[php]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[python]
symbol = "üêç "
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$pyenv_prefix$version$virtualenv]($style)[ÓÇ∞](fg:#094D92)"

[ruby]
symbol = "Óàû "
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version](fg:black bg:#094D92)(fg:black bg:#094D92)[ÓÇ∞](fg:#094D92)"

[rust]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[scala]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[swift]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"

[shell]
fish_indicator = ""
bash_indicator = "bash "
zsh_indicator = "zsh "
powershell_indicator = ""
format = "[$indicator](fg:#2B50AA)"
disabled = false
[shlvl]
symbol = "ÓØá "
style = "fg:black bg:#2B50AA"
format = "[ÓÇ∞](fg:black bg:#2B50AA)[$symbol$shlvl]($style)[ÓÇ∞](fg:#2B50AA)"
disabled = false

[terraform]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$workspace]($style)[ÓÇ∞](fg:#094D92)"

[username]
style_user = "#0370C0"
style_root = "#C00311"
format = "[ÓÇ∞](fg:black bg:$style)[$user](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[vagrant]
style = "fg:black bg:#094D92"
format = "[ÓÇ∞](fg:black bg:#094D92)[$symbol$version]($style)[ÓÇ∞](fg:#094D92)"
