command_timeout = 1000
right_format = """$time"""

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Code" = "ğŸ‘¨â€ğŸ’» Code"
"Cursos" = "î¸  Cursos"
"config" = "ï£ "

[time]
disabled = false
style = "#939594"
format = "[$time]($style)"

[aws]
style = "bg:#9ECFD4 fg:black"
symbol = "â˜ "
format = "[î‚°](fg:black bg:#9ECFD4)[$symbol$profile]($style)[î‚°](fg:#9ECFD4 bg:black)"

[character]
success_symbol = "[â¯](#3BC1A8)"
error_symbol = "[âœ—](#ff4b00)"

[cmd_duration]
style = "#9ECFD4"
min_time = 1
format = "[î‚°](fg:black bg:#9ECFD4)[ó±‘ ó°¥” $duration](bg:$style fg:black)[î‚°](fg:$style)"

[directory]
style = "#016B61"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[î‚°](fg:black bg:#016B61)[$path[$read_only](bg:$style fg:black)](bg:$style fg:black)[î‚°](fg:$style)"
read_only = " ï€£ "

[docker_context]
style = "fg:black bg:#70B2B2"
symbol = "ğŸ³  "
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$context]($style)[î‚°](fg:#70B2B2)"

[git_branch]
style = "#70B2B2"
format = "[î‚°](fg:black bg:$style)[ $symbol$branch](fg:black bg:$style)[î‚°](fg:$style)"

[git_commit]
style = "#70B2B2"
format = "\b[ ](bg:$style)[\\($hash$tag\\)](fg:black bg:$style)[î‚°](fg:$style)"

[git_state]
style = "#70B2B2"
format = "\b[ ](bg:$style)[ \\($state( $progress_current/$progress_total)\\)](fg:black bg:$style)[î‚°](fg:$style)"

[git_status]
style = "#70B2B2"
format = "(\b[ ](bg:$style fg:black)$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind[î‚°](fg:$style))"
conflicted = "[ï± ](bold fg:88 bg:#70B2B2)[ ï‘€ ${count} ](fg:black bg:#70B2B2)"
staged = "[ï§ $count ](fg:black bg:#70B2B2)"
modified = "[ï£ª ${count} ](fg:black bg:#70B2B2)"
renamed = "[ï€« ${count} ](fg:black bg:#70B2B2)"
deleted = "[ï€” ${count} ](fg:black bg:#70B2B2)"
untracked = "[?${count} ](fg:black bg:#70B2B2)"
stashed = "[ï’‡ ${count} ](fg:black bg:#70B2B2)"
ahead = "[ïƒ® ${count} ](fg:#523333 bg:#70B2B2)"
behind = "[ïƒ­ ${count} ](fg:black bg:#70B2B2)"
diverged = "[ï± ](fg:88 bg:#70B2B2)[ ï­€ ](fg:black bg:#70B2B2)[ïƒ® ${ahead_count} ](fg:black bg:#70B2B2)[ïƒ­ ${behind_count} ](fg:black bg:#70B2B2)"

[golang]
symbol = "ğŸš€ "
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[helm]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol($version)]($style)[î‚°](fg:#70B2B2)"

[java]
symbol = "ïƒ´ "
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[kotlin]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[kubernetes]
format = "[î‚°](fg:black bg:#09637E)[$symbol$context](fg:black bg:#09637E)[î‚°](fg:#09637E)"
disabled = false

[memory_usage]
style = "#9ECFD4"
symbol = "ï‰€  ğŸš€"
format = "[î‚°](fg:black bg:#9ECFD4)[$symbol$ram](bg:#9ECFD4 fg:black)[î‚°](fg:#9ECFD4)"
threshold = 1
disabled = false

[nodejs]
style = "green"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol($version)](fg:black bg:#70B2B2)[î‚°](fg:#70B2B2)"

[ocaml]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[package]
disabled = true

[php]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[python]
symbol = "ğŸ "
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$pyenv_prefix$version$virtualenv]($style)[î‚°](fg:#70B2B2)"

[ruby]
symbol = "îˆ "
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version](fg:black bg:#70B2B2)(fg:black bg:#70B2B2)[î‚°](fg:#70B2B2)"

[rust]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[scala]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[swift]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"

[shell]
fish_indicator = ""
bash_indicator = "bash "
zsh_indicator = "zsh "
powershell_indicator = ""
format = "[$indicator](fg:#09637E)"
disabled = false
[shlvl]
symbol = "î¯‡ "
style = "fg:black bg:#09637E"
format = "[î‚°](fg:black bg:#09637E)[$symbol$shlvl]($style)[î‚°](fg:#09637E)"
disabled = false

[terraform]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$workspace]($style)[î‚°](fg:#70B2B2)"

[username]
style_user = "#0370C0"
style_root = "#C00311"
format = "[î‚°](fg:black bg:$style)[$user](fg:black bg:$style)[î‚°](fg:$style)"

[vagrant]
style = "fg:black bg:#70B2B2"
format = "[î‚°](fg:black bg:#70B2B2)[$symbol$version]($style)[î‚°](fg:#70B2B2)"
